Add axum support
meilisearch/deserr pull request #30
Opened 2023-02-02 10:15 UTC by oknozor

## What does this PR do?

This PR add deserr support for axum via the `AxumJson` wrapper type. 

Note that unlike the actix-web feature serde is needed to provide a [`axum::IntoResponse`](https://docs.rs/axum/latest/axum/response/trait.IntoResponse.html) blanquet implementation for `T: serde::Serialize`. 

## Misc
- Added crates.io and doc.rs badges on the README

2023-02-02 11:25 UTC, irevoire requested changes
Nice PR!

I have a few comments that all come down to the same thing; we're not generic enough on the error type.

You can see it easily if you try to return a `QueryParamError` in the `deserr` example like that;
```rust
async fn deserr(item: AxumJson<Query, QueryParamError>) -> AxumJson<Query, QueryParamError> {
    item
}
```

This should work without requiring the user to implement anything specific I think :thinking:

2023-02-02 11:25 UTC, irevoire commented on examples/actix_web_server/Cargo.toml
> +publish = false
nice

2023-02-02 11:25 UTC, irevoire commented on src/lib.rs
> +// #[cfg(feature = "axum")]
```suggestion
#[cfg(feature = "axum")]
```

2023-02-02 11:25 UTC, irevoire commented on examples/axum/src/main.rs
> +/// This handler uses the official `AxumJson` deserr
```suggestion
/// This handler uses the official `AxumJson` deserr extractor
```

2023-02-02 11:25 UTC, irevoire commented on src/axum/serde_json.rs
> +}
We should let the end user decide which kind of error they want to return.

```suggestion
#[derive(Debug)]
pub enum AxumJsonRejection<E: DeserializeError> {
    DeserrError(E),
    JsonRejection(JsonRejection),
}
```

2023-02-02 11:25 UTC, irevoire commented on src/axum/serde_json.rs
> +}
```suggestion
#[async_trait]
impl<T, S, B, E: DeserializeError> FromRequest<S, B> for AxumJson<T, E>
where
    T: Deserr<E>,
    E: DeserializeError + 'static,
    B: HttpBody + Send + 'static,
    B::Data: Send,
    B::Error: Into<BoxError>,
    S: Send + Sync,
{
    type Rejection = AxumJsonRejection<E>;

    async fn from_request(req: Request<B>, state: &S) -> Result<Self, Self::Rejection> {
        let Json(value): Json<serde_json::Value> = Json::from_request(req, state).await?;
        let data = deserr::deserialize::<_, _, _>(value)?;
        Ok(AxumJson(data, PhantomData))
    }
}
```

2023-02-02 11:25 UTC, irevoire commented on src/axum/serde_json.rs
> +}
```suggestion
```

I don't think we can keep this while being fully generic over the error type.

2023-02-02 11:25 UTC, irevoire commented on src/axum/serde_json.rs
> +}
Maybe in the previous comments, we were supposed to also constraint `E` to implement `IntoResponse`?

2023-02-02 11:25 UTC, irevoire commented on src/axum/serde_json.rs
> +}
This is nice though, it will help someone who don't want to use his own error type :+1:

2025-02-01 13:00 UTC, Bricklou commented
Hi, any update about this PR ?

2025-02-11 10:11 UTC, irevoire commented
Closed in favor of #43

2025-02-11 10:11 UTC, closed without merging